version: '3'
services:
  app:
    image: budget-manager
    build: .
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - "./credentials_example.js:/usr/share/nginx/html/credentials.js"
    restart: always